#libraries used in this project

#install.packages("readxl")
#install.packages("fitdistrplus")
#install.packages("truncnorm")
#install.packages("ggplot2")
#install.packages("ggfortify")
#install.packages("zoo")
#install.packages("forecast")
#install.packages("dygraphs")
#install.packages("plyr")
#install.packages("DBEST")
#install.packages("openxlsx")
#install.packages(fpp2)
#install.packages(quantmod)

library(readxl)
library(fitdistrplus)
library(truncnorm)
library(ggplot2)
library(ggfortify)
library(zoo)
library(forecast)
library(dygraphs)
library(plyr)
library(DBEST)
library(openxlsx)
library(fpp2)
library(quantmod)

